services:
  url-shortener:
    build:
      context: .
    container_name: url-shortener
    restart: always
    depends_on:
      - mongodb
      - zookeeper
    ports:
      - "8000:8000"
    env_file:
      - .env
    command:  >
      sh -c "
        ./wait-for-it.sh mongodb:27017 -t 60 -- echo 'MongoDB is up' &&
        ./wait-for-it.sh zookeeper:2181 -t 60 -- echo 'Zookeeper is up' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db

  zookeeper:
    image: zookeeper:3.9
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
      - "8080:8080"

volumes:
  mongo_data:
