services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
    container_name: backend
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
    env_file:
      - .env
    command:  >
      sh -c "
        ./wait-for-it.sh mongodb:27017 -t 60 -- echo 'MongoDB is up' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    depends_on:
     - backend
    ports:
      - "3000:3000"
    environment:
      API_URL: "http://backend:8000"

volumes:
  mongo_data:
